### PR TITLE
Add style and list-styles options

### PR DESCRIPTION
**Pull request by CIAvash**
- The default style is set to `dracula`
- Background color of style gets used for window background color
- If tokens have missing colors, white or black are used based on
contrast to background. Same thing happens for line numbers.

### CODE REVIEW

**Comment by matsuyoshi30** [comment]
Hi @CIAvash, thanks for your contribution! It looks great to me, so please add the golden file in order to test selecting a `style` option (add script like `cmd/germanium/testdata/default.sh`, and do `make gentest`).

**Comment by CIAvash** [comment]
I already had created `.sh` test files and `.png` files(manually). But since `germanium` was in `.gitignore` file, it was ignoring the `germanium` folder too, so I didn't notice that my test files were ignored.

I also ran the `make gentest` command, but `go test` said no test files, it was eating the flag, so I put the `-gen_golden_files` flag at the end.

**Comment by CIAvash** [comment]
I just noticed that you fixed the `make` file. So I amended my commit and pulled from main and force pushed my commit.

**Comment by matsuyoshi30** [comment]
@CIAvash Sorry for forgetting to tell you that I've fixed Makefile. It looks great to me. Thanks!

**Pull request merged**
